weightCreeper: 120
weightChargedCreeper: 170
weightSkeleton: 320
weightWitherSkeleton: 420
weightStray: 540
weightSpider: 690
weightSpiderJockey: 740
weightZombie: 890
weightZombieVillager: 915
weightHusk: 1035
weightChickenJockey: 1085
weightSlime: 1205
weightGhast: 1255
weightZombiePigman: 1455
weightChickenJockey2: 1505
weightEnderman: 1605
weightCaveSpider: 1725
weightBlaze: 1825
weightMagmaCube: 1945
weightRavagerBossSloth: 2050
weightBat: 2210
weightWitch: 2310
weightEndermite: 2360
weightDrowned: 2480
weightPillager: 2580
weightRavager: 2680
weightZoglin: 2780
weightPig: 3280
weightSheep: 3780
weightCow: 4280
weightChicken: 4780
weightWolf: 5280
weightRedMooshroom: 5430
weightBrownMooshroom: 5580
weightOcelot: 5780
weightCat: 6280
weightHorse: 6480
weightDonkey: 6680
weightMule: 6880
weightZombieHorse: 6930
weightSkeletonHorse: 7080
weightRabbit: 7230
weightPolarBear: 7350
weightLlama: 8510
weightVillager: 8530
weightParrot: 8680
weightTurtle: 8830
weightFox: 9080
weightArcticFox: 9330
weightPanda: 9480
weightWanderingTrader: 9500
weightTraderLlama: 9600
weightBee: 9850
weightStrider: 10200
weightStriderJockey: 10250
weightGoat: 11000

RandomUpperbound: 11001
